name: Node.js CI (Windows)
on:
  push:
    branches: [ main ]       
  pull_request:
    branches: [ main ]  
    
  workflow_dispatch:     
  
jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check coverage
        run: npm run coverage
